list: $/pensoft/casestudies/models/data/columns.yaml
modelClass: Pensoft\Casestudies\Models\Data
title: CaseStudies
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/casestudies/casestudies/update/:id'
